version: '3.9'

services:
  web:
    build: .
    command: bash -c "python3.9 manage.py makemigrations && python3.9 manage.py migrate && python3.9 manage.py runserver 0.0.0.0:8137"
    volumes:
      - .:/app
      - mediadata:/app/media
      - logdata:/app/logs
    ports:
      - "8137:8137"
    container_name: Crag
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    restart: always
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=database_1.db
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=kJGnTXBT
    container_name: DataBase
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    environment:
      - TZ=Europe/Moscow
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=BfDVBPsNSf
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build: .
    command: celery -A crag worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    container_name: Celery
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    restart: always

  celerybeat:
    build: .
    command: celery -A crag beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    container_name: Celery_Beat
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    restart: always
  elasticsearch:
    image: elasticsearch:8.7.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    container_name: Elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: always

  graylog:
    image: graylog/graylog:4.1
    container_name: Graylog
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://195.2.80.251:9000/
    restart: always
    ports:
      - "9000:9000"  # Порт Graylog веб-интерфейса
      - "12201:12201/udp"  # Порт Graylog GELF UDP input

volumes:
  dbdata:
  mediadata:
  logdata:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/logs
      o: bind
