version: '3.9'

services:
  web:
    build: .
    command: bash -c "python3.9 manage.py makemigrations && python3.9 manage.py migrate && python3.9 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    container_name: creg
    environment:
      - TZ=Europe/Moscow
    restart: always
