version: '3.9'

services:
  web:
    image: dr.boardmaps.ru/devops/creg:latest
    command: bash -c "python3.9 manage.py makemigrations && python3.9 manage.py migrate && python3.9 manage.py runserver 0.0.0.0:8137"
    volumes:
      - /mnt/swarm_volume_1/creg:/app
      - /mnt/swarm_volume_1/creg/mediadata:/app/media
      - /mnt/swarm_volume_1/creg/logdata:/app/logs
    ports:
      - "8137:8137"
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgres://sa:kJGnTXBT@db:5432/database_1
    depends_on:
      - db
      - rabbitmq
    deploy:
      mode: replicated
      replicas: 1

  db:
    image: postgres:13
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_DB=database_1
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=kJGnTXBT
    volumes:
      - /mnt/swarm_volume_1/creg/dbdata:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=BfDVBPsNSf
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      mode: replicated
      replicas: 1

  celery:
    image: dr.boardmaps.ru/devops/creg:latest
    command: celery -A crag worker --loglevel=info
    volumes:
      - /mnt/swarm_volume_1/creg:/app
    depends_on:
      - db
      - rabbitmq
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgres://sa:kJGnTXBT@db:5432/database_1
    deploy:
      mode: replicated
      replicas: 1

  celerybeat:
    image: dr.boardmaps.ru/devops/creg:latest
    command: celery -A crag beat -l info
    volumes:
      - /mnt/swarm_volume_1/creg:/app
    depends_on:
      - db
      - rabbitmq
    environment:
      - TZ=Europe/Moscow
      - DATABASE_URL=postgres://sa:kJGnTXBT@db:5432/database_1
    deploy:
      mode: replicated
      replicas: 1
